### ISSUE TITLE
Strange characters in terminal

### ISSUE THREAD

**Issue by nickbe** [stefanhaustein/TerminalImageViewer#38] opened 2019-02-21 22:54 UTC
tiv only works halfway as expected when using the -256 option. But even then I can see strange characters inside the blocks:

![grafik](https://user-images.githubusercontent.com/10890765/53207446-02854b00-3634-11e9-86c5-f7ced1aa89f2.png)

Any idea how to get rid of that?
I'm using kitty/putty in windows.

**Comment by stefanhaustein** [comment] 2019-02-21 22:59
Hack: comment out the unsupported characters here:
https://github.com/stefanhaustein/TerminalImageViewer/blob/f80071243f68fa01b34a037477366673e4e87862/src/main/cpp/tiv.cpp#L29

Longer term: Disable characters using a flag.

Did you try the -0 option?

**Comment by nickbe** [comment] 2019-02-22 00:36
Yes I did, but then the image gets messed up completely.
I've just tried the latest daily build of putty and there everything works just fine. So this seems to be a kitty problems.

**Comment by GottZ** [comment] 2019-02-22 03:12
seems to me like you should switch your console font to something like fira code or inconsolata
(using windows is no excuse for ignoring unicode additions)

**Comment by stefanhaustein** [comment] 2019-02-24 00:05
Closing as the problem is addressed by using a new version of kitty

**Closed by stefanhaustein** 2019-02-24 00:05 UTC
Labels: bug, invalid
